# QuickServe Backend — Application Properties

spring.application.name=backend

# Server
server.port=8080

# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/quickserve
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a8d5c48b61e2f7b8d447a195f33333333333333333333333333333333333333333333333333333333333333333333333
app.jwt.expiration-ms=86400000
